{% set version = "0.1.0" %}

package:
  name: xdmfwrite_highfive
  version: {{ version }}

source:
  url: https://github.com/tdegeus/XDMFWrite_HighFive/archive/v{{ version }}.tar.gz
  sha256: c9979aaf05eaac3fb7ecdb7dc696ddcccfb8bba338bcb1eedc71098e239d09d4

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host:
    - highfive
  run:
    - highfive

test:
  commands:
    - test -f ${PREFIX}/include/XDMFWrite_HighFive.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/XDMFWrite_HighFive/XDMFWrite_HighFiveConfig.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\XDMFWrite_HighFive.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\XDMFWrite_HighFiveConfig.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/tdegeus/XDMFWrite_HighFive
  license: MIT
  license_file: LICENSE
  summary: Write XDMF files to interpret HDF5 files.
  description: Write XDMF files to interpret HDF5 files.
  doc_url: https://github.com/tdegeus/XDMFWrite_HighFive
  dev_url: https://github.com/tdegeus/XDMFWrite_HighFive

extra:
  recipe-maintainers:
    - tdegeus
